### ISSUE TITLE
Block by PR

### ISSUE THREAD

**Issue by amr-eniou-3r** [z0al/dependent-issues#127]
Hello,

I wonder if your bot could work by Pull Requests instead of issues as not everyone uses Github issues

Thanks

**Comment by z0al** [comment]
Hey there. Do you want to use a PR as a dependency? e.g. `depends on #my-pr-number` ? 

If yes, then that's actually supported.

**Comment by amr-eniou-3r** [comment]
@z0al thanks a lot
