### ISSUE TITLE
Job aborts with "Error: Resource not accessible by integration"

### ISSUE THREAD

**Issue by ulope** [z0al/dependent-issues#2]
We've just added this to our repo but unfortunately it doesn't seem to work.

The "Checking #PR" step aborts with `Error: Resource not accessible by integration`
See: https://github.com/raiden-network/raiden/runs/1486971356?check_suite_focus=true

**Comment by ulope** [comment]
Looks like this is a known issue with github actions and forked PRs.
Apparently using `pull_request_target` instead of `pull_request` solves the problem: https://github.blog/2020-08-03-github-actions-improvements-for-fork-and-pull-request-workflows/#improvements-for-public-repository-forks

Will try and report back.

**Comment by ulope** [comment]
Ok this fixed the issue.
So maybe changing the documentation to use the `pull_request_target` trigger would make sense.

**Comment by z0al** [comment]
Thanks for investigating this @ulope. I will read more about this in the morning and update the docs accordingly :+1:

**Comment by z0al** [comment]
You are right. I updated the docs accordingly.
