### ISSUE TITLE
Compact comment footer

### ISSUE THREAD

**Issue by MarcinOrlowski** [z0al/dependent-issues#217]
Can the comment footer be either configurable or at least more compact? I.e. can the separating line:

> 💡  To add or remove a dependency please update this issue/PR description.
>
> Brought to you by [Dependent Issues](https://github.com/z0al/dependent-issues) (robot ). Happy coding!

be removed so the footer takes 2 instead of 3 lines? Or even better, can it be compacted into just one line, like:

> 💡 [Dependent Issues](https://github.com/z0al/dependent-issues): To add or remove a dependency please update this issue/PR description.

PS: the trailing space in "robot" is not needed (and I think "bot" fits here better than "robot").

**Comment by z0al** [comment]
I don't mind it much but don't understand what difference it makes. Can you elaborate maybe? 

> the trailing space in "robot" is not needed (and I think "bot" fits here better than "robot").

It's actually `:robot:` which _should_ render 🤖  indicating a "bot" :)

**Comment by MarcinOrlowski** [comment]
If that is supposed to b emoji then that's different story. I meant that "robot" is usually used in connotation with physical unit (machine), while "bot" can be used also to refer to anything being autonomous/automated, even if only in software. 

Also why you do not use name "Dependabot". I like it :) and it instantly means a tool while "Dependent Issues" looks like link to "Issues" section :)

**Comment by z0al** [comment]
> Also why you do not use name "Dependabot".

Because it's already used by a [company](https://dependabot.com/) (then later [GitHub](https://docs.github.com/en/code-security/supply-chain-security/keeping-your-dependencies-updated-automatically/about-dependabot-version-updates)) and would be very confusing

**Comment by MarcinOrlowski** [comment]
It's a pity. Anyway, what about first part of the request - cramming the footer into 1 line?

**Comment by z0al** [comment]
> I don't mind it much but don't understand what difference it makes. Can you elaborate maybe?

:)

**Comment by MarcinOrlowski** [comment]
I till be more compact and not stick out too much? In fact I'd be happy if I can disable (i.e. via config option) the "To add or remove a dependency please update this issue/PR description." paragraph. The result will be as I wanted:

Before

![before](https://user-images.githubusercontent.com/8041294/130314182-8a881861-35e0-466c-a240-1c9514c6fc51.png)

After:

![after](https://user-images.githubusercontent.com/8041294/130314184-403c9c6e-b1ee-4f5b-a726-50bb172f9ee9.png)

**Comment by MarcinOrlowski** [comment]
Any thoughts on this?

**Comment by z0al** [comment]
Hey, sorry. I'm not convinced removing the tip (`To add or remove ...`) makes the messaging clear enough especially for first-time users. I'd like to leave it as is

Ideally, in future the action can allow custom message templates via configuration. I'd happily accept a PR that implements something similar.
