### ISSUE TITLE
Unconditional blocker

### ISSUE THREAD

**Issue by MarcinOrlowski** [z0al/dependent-issues#239]
Can you add unconditional blocker to your action? If description contains specified string, then PR is blocked as long as this keyword exist. I'd then have and use i.e. `DO_NOT_MERGE`

**Comment by z0al** [comment]
That's outside the scope of this action. However, there are plenty of other options available. Here are some options you could try:

* [DO NOT MERGE – as an action](https://github.com/wip/action)
* [Block PR Merges if Keyword Found](https://github.com/marketplace/actions/block-pr-merges-if-keyword-found)
