### ISSUE TITLE
Warning: Unexpected input(s) 'ignore_dependabot', valid inputs are ['label', 'check_issues', 'keywords', 'comment']

### ISSUE THREAD

**Issue by arjunadeltoso** [z0al/dependent-issues#440]
Copy pasted the example workflow yaml in the README, got this warning in github run logs on "set up jobs" step.

**Comment by castello-span** [comment]
I had the same issue, turns out that after creating a PAT and referencing it in the `yml` file the error goes away. The readme covers how to create a PAT.

**Comment by z0al** [comment]
This warning is there because `ignore_dependabot` is not mentioned as an option in the [action.yaml](https://github.com/z0al/dependent-issues/blob/main/action.yaml). Should be a quick fix. PRs are welcome.
